---
- hosts: all
  roles:
  - role: '{{ playbook_dir }}'
  tasks:
  - command: /usr/local/bin/terragrunt --version
    register: terragrunt_test_output
  - debug:
      msg: '{{ terragrunt_test_output.stdout }}'
